version: 1.0.{build}
pull_requests:  
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: oguzhansoykan@outlook.com
  nuget_password:
    secure: w73Xs1Is7iK/DtAOf0XTHg==
before_build:
- cmd: dotnet.exe restore
test:
 assemblies: test\FluentAssemblyScanner.Tests\bin\Debug\net452\win7-x64\FluentAssemblyScanner.Tests.dll
nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
 cmd: dotnet pack "src\FluentAssemblyScanner" -c "Release" -o "nupkg/"
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: liSTqN52OJQy9fZJk6gubSgYBAy4EXcEPCDSCLJ/3T9cZufzpTwvBlGPLX+iP2n9
  artifact: /.*\.nupkg/
